default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: the_great_db_development

test:
  <<: *default
  database: rails-watch-list_test

production:
  <<: *default
  database: the_great_db_production
  username: the_great_db
  password: <%= ENV["THE_GREAT_DB_DATABASE_PASSWORD"] %>
